name: Renovate Bot

on:
  schedule:
    - cron: "0 9 * * 1"
    # pull_request:
    #   branches:
    #     - '*'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.15
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          LOG_LEVEL: debug
