name: Renovate Bot

on:
  schedule:
    - cron: "0 9 * * 1"
    # pull_request:
    #   branches:
    #     - '*'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Renovate
        run: npx renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_AUTODISCOVER: true
