name: Test and Build

on:
  push:
    branches:
      - "*"

jobs:
    test:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests with Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test

    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm install

            - name: Set Git Identity
              run: |
                git config --global user.email "github-actions@github.com"
                git config --global user.name "GitHub Actions"

            - name: Deploy on Visual Studio Marketplace
              run: |
                COMMIT_MSG=$(git log -1 --pretty=%B)
                if [[ "$COMMIT_MSG" == *"#major"* ]]; then
                  VERSION_BUMP=major
                elif [[ "$COMMIT_MSG" == *"#minor"* ]]; then
                  VERSION_BUMP=minor
                else
                  VERSION_BUMP=patch
                fi

                # Force version increment in package.json
                npm version $VERSION_BUMP --no-git-tag-version --force
                
                # Get the new version from package.json after the increment
                NEW_VERSION=$(node -p "require('./package.json').version")
                
                # Publish using the exact version, not a bump type
                npx vsce publish $NEW_VERSION
    
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}
