name: Test and Build

on:
  push:
    branches:
      - "*"

jobs:
    test:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests with Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test

    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm install

            - name: Set Git Identity
              run: |
                git config --global user.email "github-actions@github.com"
                git config --global user.name "GitHub Actions"

            - name: Deploy on Visual Studio Marketplace
              run: |
                COMMIT_MSG=$(git log -1 --pretty=%B)
                if [[ "$COMMIT_MSG" == *"#major"* ]]; then
                  npm version major --no-git-tag-version --force
                elif [[ "$COMMIT_MSG" == *"#minor"* ]]; then
                  npm version minor --no-git-tag-version --force
                else
                  npm version patch --no-git-tag-version --force
                fi
                
                npx vsce publish

                # Commit the version change back to the repository
                git add package.json
                git commit -m "Bump version [skip ci]"
                git push
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}
                GITHUB_TOKEN: ${{ github.token }}
